modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/cech12/BrickShears/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="woodenhopper"
    version="${file.jarVersion}"
    displayName="Wooden Hopper"
    displayURL="https://github.com/cech12/WoodenHopper"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Wooden Hopper.
    '''
[[dependencies.woodenhopper]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.57,32)"
    ordering="NONE"
    side="BOTH"
[[dependencies.woodenhopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"