modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/cech12/BrickShears/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="woodenhopper"
    version="${file.jarVersion}"
    displayName="Wooden Hopper"
    displayURL="https://github.com/cech12/WoodenHopper"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Wooden Hopper.
    '''
[[dependencies.woodenhopper]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.woodenhopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"